language: node_js
node_js:
  - "8.1"
env:
  global:
  - secure: GqNPp2suMSzNL+V26tLcEnNeZTGbDxV2Zr4urZvR0WNpjX9DrjrJGvkKTih2jRAn/D7DO2PdkWWvz5m8fpXZZ1CgfA+ow79F9qMSMI2AfgngSi+6ri60NwQAT4oLfwdN3AtNW6g/hpvlhiQvjCJ15GigAaOeNB7F6mmhU+qVdrvEaTPTAuw9ZODoLKZTjmMUw+gyjgowuBKxJKRbw4xaK27vt3kFksT0IlCmCkSQHQfR6M8q3P1B7ZatD7utvRebne4C2/a1TydUu5Kg0EsMdEWrAKLErX7HMBhZWusbQajzWorNOfzKY86+gWN+UZCzZj8UenQ2rZsXnFsW41nrEI1QkB36aMEXhtLSre7qk6ae689ZYpK5NTzAR4J4mCWFI6Qr/nW0tD2VAoS1s8s8QG7PIQKggsijSCR6Os3ZHzELvddpg3Fek4VDSgxX5BEjEdIH+4SRA+HCP0cQ0jkpNiRmy6UmRCJoeDWZ34YUyeLmR/DWEN0u374Nn/WGH1VAb0bsVAMTO96f/lA0XLiDVVkPsSb0ukJa1KTbFi1FFfG7v5kF7NQHWo1PtU763Gv/2MQHhH4XLxURnceaQqXEcFCqmpg34yOt84ZN8mU7LHDIfoSzQ7zOmrq4DL7xdGWVDWXiSLP26GckiScURb8Y5m7Kt0rFXQtXHl3z1+J3NQw=
  - secure: lFkasihIzrJTydTy//AQYUFA2Wip5aIkVkFgbCdPHPCuaN85prZaz6RoUVGA08sev7+lybhQvTH3ZWwfEA0yJJ06bd7TDr/vHpaoSLNGlM4aTdugLYHESSfnPH/zFKpjUm00/uRFQHLa5FZA80a4VPY6KB7TJgj0j0EVR7RualEvoYqXiRe3KZEs4SbN8H1vZ36vCzD4mGPJXT/uCUjXmHD4JOCGc58RXfW+yc62xDhwoLfD4j6laRuN8J1LvLSH2yQsSUIvjBjmZulBf9EMe5D62HXE9FJ2ifZcZ7QIUCQA271fzCGhaCYI2BmaqnpEw8UY9I4vebtnx7B6pagkxG6Beq+vYhO/ClMtHGwLo6+vJzKOabB98a21N2hUAspiKLVNXjTaAELJOyzRioiDb8z8P3CT+JKUzN4URmUvzpq8Zn5NcXD7rt6qpmVaetowtXXGUNvKTDe7dq+VWEXAsk7PMeJlmRLmjaiP98L0c/dWADD5B+KwbonECuqeQ6DcpPXTlyx2dnQ3WYsszSMrWow4YVRafoLA0/FQAI6Ux+JDuL8v/G51nk5JPDU89U3zFf8Nep1rqrA/NCGQvKfCXhh0WYSjSjUmO98IgwxhISNwabyzu2CVlZAuq461VO3/3W9UCUD8yfa2oXZcyl4ZjrYzjf9YKJJMbEeLsggMTII=

services:
  - docker


# First we run a script that creates the zip file for lambda with all the compiled libraries.
before_deploy:
  - cd lambda ; ./prepare.sh

#Then we deploy the zip to lambda, using the AWS user in the env variable
deploy:
  provider: lambda
  function_name: "cryptario-stage"
  region: "eu-west-1"
  zip: "lambda/lambda.zip"
  role: "arn:aws:iam::160991186365:role/cryptario"
  handler_name: "handler"
  runtime: "nodejs8.10"

# ensure that deployment only happens when merging into the master branch
stages:
  - name: deploy
    # require the branch name to be master (note for PRs this is the base branch name)
    if: branch = master

