const dictionary = {
  a: ['a'], 
  about: ['re', 'on', 'c', 'ca'],
  abstainer: ['tt'],
  account: ['ac'],
  accountant: ['ca'],
  ace: ['a'],
  afternoon: ['pm'],
  alien: ['et'],
  all: ['a'],
  alpha: ['a'],
  american: ['am', 'us'],
  'ancient city': ['ur '],
  are: ['a'],
  area: ['a'],
  army: ['ta'],
  article: ['a', 'an', 'the'],
  artist: ['ra'],
  'at home': ['in'],
  avenue: ['ave'],
  bachelor: ['ba', 'b'],
  bearing: ['any compass point'],
  before: ['ere'],
  beginner: ['l'],
  bend: ['z', 'u'],
  bible: ['ot', 'nt', 'rv'],
  big: ['os'],
  bill: ['ac', 'ad'],
  billion: ['b', 'bn'],
  bishop: ['b', 'rr'],
  black: ['b'],
  book: ['b', 'ot', 'nt'],
  books: ['ot', 'nt'],
  born: ['b'],
  bravo: ['b'],
  british: ['b'],
  business: ['co'],
  car: ['rr'],
  castle: ['r'],
  catholic: ['c', 'rc'],
  caught: ['c'],
  celsius: ['c'],
  century: ['c'],
  chapter: ['c', 'ch'],
  charlie: ['c'],
  christ: ['x'],
  church: ['ce', 'ch', 'rc', 'ec'],
  circa: ['c', 'ca'],
  circle: ['o'],
  city: ['ny', 'la', 'ec'],
  classy: ['u'],
  club: ['c'],
  cocaine: ['c'],
  cold: ['c'],
  communications: ['pr'],
  communist: ['red'],
  companion: ['ch'],
  company: ['co'],
  composer: ['arne [not actually an abbreviation]'],
  computing: ['it'],
  concerning: ['re'],
  conservative: ['c'],
  coordinate: ['x', 'y '],
  copper: ['p', 'd', 'pc', 'cu'],
  court: ['ct'],
  credit: ['cr'],
  'cricket side': ['xi', 'on', 'off', 'leg'],
  current: ['ac', 'dc', 'i', 'in'],
  daughter: ['d'],
  day: ['d'],
  dead: ['d'],
  decoration: ['om', 'cbe', 'etc.'],
  delta: ['d'],
  democrat: ['d'],
  density: ['d'],
  departs: ['d'],
  diamond: ['d'],
  dictionary: ['oed'],
  died: ['d'],
  direction: ['any compass point [n', 's', 'e', 'w or se', 'nw', 'sse', 'etc.]'],
  doctor: ['dr', 'doc', 'mo', 'gp'],
  drug: ['c', 'e', 'h', 'pot'],
  dry: ['tt'],
  duck: ['o'],
  duke: ['d'],
  each: ['ea', 'per'],
  earl: ['e'],
  east: ['e'],
  echo: ['e'],
  ecstasy: ['e'],
  editor: ['ed'],
  electronic: ['e'],
  eleven: ['xi'],
  encore: ['bis'],
  energy: ['e'],
  engineer: ['ce', 're'],
  english: ['e'],
  european: ['e'],
  excellent: ['a1'],
  expert: ['ace', 'pro'],
  exercise: ['pe', 'pt'],
  'extra terrestrial': ['et'],
  fahrenheit: ['f'],
  family: ['kin'],
  farthing: ['f'],
  fashionable: ['in'],
  fast: ['lent'],
  father: ['pa', 'pop', 'dad', 'fr'],
  fellow: ['f', 'don'],
  feminine: ['f'],
  fifty: ['l'],
  film: ['et', 'kes'],
  fine: ['f'],
  firm: ['co'],
  first: ['1st'],
  'first class': ['a1'],
  five: ['v'],
  fliers: ['raf'],
  following: ['f'],
  'football team': ['xi'],
  'for example': ['eg'],
  former: ['ex'],
  four: ['iv'],
  forte: ['f'],
  foxtrot: ['f'],
  function: ['sin', 'cos', 'tan'],
  general: ['lee'],
  gold: ['au', 'or'],
  golf: ['g'],
  good: ['g'],
  'good man': ['st'],
  grand: ['g', 'k', 'm'],
  gym: ['pe', 'pt'],
  hand: ['l', 'r'],
  hard: ['h'],
  heart: ['h'],
  heroin: ['h'],
  'holy man': ['st'],
  home: ['in'],
  horse: ['gg'],
  hospital: ['h'],
  hot: ['h'],
  hotel: ['h'],
  hour: ['h', 'hr'],
  hundred: ['c'],
  husband: ['h'],
  "i'm obliged": ['ta'],
  india: ['i'],
  information: ['gen'],
  internet: ['net', 'www'],
  iron: ['fe'],
  island: ['i', 'is', 'man'],
  jack: ['ab', 'os', 'tar'],
  jail: ['can'],
  journalist: ['ed'],
  judge: ['j', 'ref'],
  juliet: ['j'],
  key: ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'esc'],
  kilo: ['k'],
  king: ['k', 'r', 'er'],
  kiss: ['x'],
  knight: ['n'],
  lake: ['l'],
  latin: ['l'],
  lawyer: ['da'],
  lead: ['pb'],
  learner: ['l'],
  left: ['l'],
  liberal: ['l'],
  lima: ['l'],
  line: ['l', 'ry'],
  lines: ['ll'],
  look: ['lo'],
  loud: ['f', 'ff'],
  love: ['o'],
  low: ['moo'],
  lunch: ['meal'],
  magistrate: ['jp'],
  maiden: ['m'],
  main: ['sea'],
  male: ['m'],
  mark: ['m'],
  married: ['m'],
  mass: ['m'],
  measure: ['em', 'en'],
  medal: ['ch', 'vc', 'obe', 'om', 'gc'],
  member: ['arm', 'leg', 'toe', 'mp'],
  men: ['or', 're'],
  mercury: ['hg'],
  mike: ['m'],
  mile: ['m', 'mi'],
  million: ['m'],
  minister: ['dd'],
  minute: ['m'],
  month: ['m'],
  morning: ['am'],
  mother: ['ma', 'mum', 'dam'],
  mum: ['m', 'ma', 'mom', 'sh'],
  name: ['n'],
  navy: ['rn'],
  nazis: ['ss'],
  neat: ['ox'],
  neon: ['ne'],
  network: ['lan'],
  new: ['n'],
  newspaper: ['ft', 'organ', 'rag'],
  none: ['o'],
  noon: ['n', 'm'],
  north: ['n'],
  'north america': ['na'],
  note: ['nb', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'do', 're', 'mi', 'fa', 'so', 'la', 'ti', 'te'],
  nothing: ['o','nada'],
  november: ['n', 'nov'],
  number: ['n', 'no', 'l', 'x', 'i', 'v', 'c', 'm'],
  old: ['ex', 'o'],
  'old boy': ['ob'],
  'old city': ['ur'],
  on: ['re'],
  one: ['i', 'a', 'an'],
  operation: ['op'],
  opposed: ['v', 'vs'],
  oscar: ['o'],
  page: ['p'],
  pages: ['pp'],
  papa: ['p'],
  papers: ['id'],
  parking: ['p'],
  party: ['do', 'lab', 'lib', 'con', 'anc'],
  pawn: ['p'],
  pence: ['p', 'd'],
  penny: ['p', 'd'],
  piano: ['p'],
  point: ['n', 's', 'e', 'w', 'ne', 'nw', 'se', 'sw'],
  popular: ['in'],
  position: ['put'],
  posh: ['u'],
  pound: ['l', 'lb'],
  pounds: ['lbs'],
  power: ['p'],
  pressure: ['p'],
  priest: ['p'],
  prison: ['can', 'jug'],
  promise: ['iou'],
  provided: ['so'],
  professional: ['pro'],
  pub: ['ph'],
  quarter: ['n', 'e', 's', 'w'],
  quebec: ['q'],
  queen: ['q', 'r', 'hm', 'er'],
  question: ['q', 'qu'],
  quiet: ['sh', 'p', 'pp'],
  quietly: ['p', 'pp'],
  'quite loud': ['mf'],
  'quite quiet': ['mp'],
  railway: ['ry'],
  recipe: ['r'],
  record: ['cd', 'lp', 'ep', 'log', 'sp'],
  regiment: ['re'],
  resistance: ['r'],
  right: ['r'],
  river: ['r'],
  road: ['rd', 'ai', 'mi'],
  romeo: ['r'],
  rook: ['r'],
  rugby: ['ru', 'rl'],
  run: ['r'],
  'run out': ['ro'],
  sailor: ['tar', 'ab', 'os'],
  saint: ['st'],
  scotsman: ['ian', 'mac'],
  say: ['eg'],
  second: ['s', 'mo'],
  'second-rate': ['b'],
  see: ['v'],
  setter: ['i', 'me', 'gel'],
  shilling: ['s'],
  shirt: ['t'],
  ship: ['ss'],
  side: ['xi'],
  sierra: ['s'],
  sign: ['cancer', 'capricorn', 'pisces', 'aries', 'taurus', 'gemini', 'leo', 'virgo', 'libra', 'scorpio', 'sagittarius', 'aquarius'],
  error: ['x'],
  silver: ['ag'],
  soap: ['er'],
  socialist: ['red'],
  soft: ['p', 'pp'],
  softly: ['p', 'pp'],
  soldier: ['gi', 'rm', 're'],
  soldiers: ['men', 'or'],
  son: ['s'],
  sons: ['s'],
  south: ['s'],
  'south american': ['sa'],
  space: ['em', 'en'],
  spade: ['s'],
  sport: ['ru', 'rl'],
  square: ['s', 't'],
  state: ['al', 'ak', 'az', 'ar', 'ca', 'co', 'ct', 'de', 'fl', 'ga', 'hi', 'id', 'il', 'in', 'ia', 'ks', 'ky', 'la', 'me', 'md', 'ma', 'mi', 'mn', 'ms', 'mo', 'mt', 'ne', 'nv', 'nh', 'nj', 'nm', 'ny', 'nc', 'nd', 'oh', 'ok', 'or', 'pa', 'ri', 'sc', 'sd', 'tn', 'tx', 'ut', 'vt', 'va', 'wa', 'wv', 'wi', 'wy'],
  street: ['st', 'rd', 'way', 'ave'],
  student: ['l', 'ba', 'bsc'],
  succeeded: ['s'],
  suit: ['c', 'd', 'h', 's'],
  take: ['r'],
  tango: ['t'],
  tax: ['vat', 'ni'],
  teachers: ['nut'],
  team: ['xi'],
  tea: ['cha'],
  temperature: ['t'],
  technology: ['it', 'ict'],
  tense: ['t'],
  thanks: ['ta'],
  'that is': ['ie'],
  theologian: ['dd'],
  thousand: ['k', 'm'],
  tin: ['sn'],
  time: ['t'],
  times: ['tt', 'by', 'x'],
  ten: ['x'],
  tracks: ['ry'],
  turn: ['go', 'u'],
  uniform: ['u'],
  universal: ['u'],
  university: ['u', 'ou'],
  unknown: ['x', 'y', 'z'],
  'upper class': ['u'],
  variable: ['x', 'y', 'z'],
  versus: ['v', 'vs'],
  very: ['v'],
  victor: ['v'],
  victory: ['v'],
  volunteers: ['ta'],
  way: ['st', 'rd', 'ave'],
  web: ['net', 'www'],
  week: ['w'],
  west: ['w'],
  whiskey: ['w'],
  wide: ['w'],
  wife: ['w'],
  wine: ['asti', 'tent', 'sec'],
  with: ['w'],
  without: ['wo'],
  woman: ['she'],
  women: ['w'],
  won: ['w'],
  work: ['op'],
  worker: ['ant', 'bee'],
  working: ['on'],
  writer: ['pen'],
  writing: ['ms'],
  'x-ray': ['x'],
  yankee: ['y'],
  year: ['y', 'yr'],
  zero: ['o'],
  zulu: ['z']
}

module.exports = dictionary
