module.exports = [
  'appears in',
  'buried in',
  'camouflages',
  'characters',
  'coming from',
  'concealed',
  'concealing',
  'conceals',
  'contained',
  'content',
  'contents',
  'contributing',
  'demonstrates',
  'displaying',
  'dwells in',
  'eclipsing',
  'encloses',
  'exhibiting',
  'extract',
  'featuring',
  'featuring from',
  'from',
  'furnishes',
  'getting letters from',
  'gives',
  'has',
  'held by',
  'helping to make',
  'hidden',
  'hides',
  'hiding',
  'holds',
  'in',
  'inherent in',
  'in part',
  'inside',
  'internal',
  'intrinsic',
  'letters',
  'letters from',
  'letters of',
  'of',
  'part',
  'partial',
  'partly',
  'providing',
  'reveals',
  'secreting',
  'segment of',
  'selection',
  'showing',
  'smuggling',
  'some',
  'somewhat',
  'stores',
  'to reveal',
  'veiled',
  'veiling',
  'veils',
  'withholds',
  'within']
