module.exports = [ 'according to hearsay',
  'announced',
  'as we hear',
  'audible',
  'audibly',
  'auditor\'s',
  'aurally',
  'by the sound of it',
  'for the audience',
  'for the auditor',
  'for the listener',
  'heard',
  'hearer\'s',
  'in audition',
  'in conversation',
  'in recital',
  'in speaking',
  'in speech',
  'listener\'s',
  'on the radio',
  'overheard',
  'pronounced',
  'reported',
  'reportedly',
  'said',
  'say',
  'so it\'s said',
  'so to speak',
  'so we hear',
  'sound',
  'sounded',
  'sounding',
  'speaker\'s',
  'spoken',
  'to the audience',
  'to the auditor',
  'to the listener',
  'vocal',
  'voiced' ]
