module.exports = [
  'about',
  'around',
  'ascending',
  'back',
  'backed',
  'backing',
  'back-to-front',
  'backward',
  'brought about',
  'brought up',
  'cast up',
  'climbing',
  'coming back',
  'coming up',
  'counter',
  'flipped',
  'flipping',
  'from the bottom',
  'from the east',
  'from the right',
  'from the south',
  'going back',
  'going north',
  'going round',
  'going up',
  'going west',
  'lifted',
  'looking back',
  'looking up',
  'northbound',
  'over',
  'overturned',
  'raised',
  'raising',
  'retreat',
  'retreating',
  'retrograde',
  'retrospective',
  'reversed',
  'reversing',
  'revolutionary',
  'rising',
  'round',
  'sent back',
  'sent up',
  'shown up',
  'taken up',
  'turn',
  'turned',
  'turning',
  'turns',
  'turns up',
  'up',
  'upended',
  'upset',
  'upwardly mobile',
  'westbound',
  'written up']
