module.exports = ['abridged',
  'almost',
  'back off',
  'clipped',
  'curtailed',
  'cut short',
  'detailed',
  'early closing',
  'endless',
  'falling short',
  'finish off',
  'for the most part',
  'incomplete',
  'interminable',
  'lacking finish',
  'missing the last',
  'most',
  'mostly',
  'nearly',
  'not completely',
  'not fully',
  'not quite',
  'tailless',
  'unending',
  'unfinished',
  'without end']
