module.exports = ['after commencement',
  'beginning to go',
  'beheaded',
  'beheading',
  'decapitated',
  'first off',
  'headless',
  'head off',
  'initially lacking',
  'leaderless',
  'losing opener',
  'missing the first',
  'needing no introduction',
  'not beginning',
  'not commencing',
  'not starting',
  'start off',
  'start to go',
  'scratch the head',
  'strike the head',
  'uninitiated',
  'unstarted']
